[unstable]
# makes sure standard memory built-ins are compiled with our kernel 
# so we can avoid having to reimplement with "#[no_mangle]" and risk
# incorrect implementation
build-std-features = ["compiler-builtins-mem"]
# makes sure the core is recompiled for our custom targets, 
# otherwise cargo build will only work on standard supported host
# triples (e.g. x86_64-unknown-linux-gnu)
build-std = ["core", "compiler_builtins"]

# set default build target
[build]
target = "x86_64-os_practice.json"

# calls 'bootimage runnner' on a call to 'cargo run' which will 
# automatically link the executable to the bootloader and boot it in
# QEMU
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
